[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fhefedavg-v1-35"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]==1.20.0",
    "flwr-datasets[vision]==0.5.0",
    "torch==2.8.0",
    "torchvision==0.23.0",
    "prometheus_client>=0.19.0"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "Kristian Teig Grønvold"

[tool.flwr.app.components]
serverapp = "fhefedavg.server_app:app"
clientapp = "fhefedavg.client_app:app"

[tool.flwr.app.config]
# General paramters
num-clients = 3 # Number of clients expected to connect.
num-server-rounds = 3
fraction-fit = 1 # Need all clients to train for experiments.
local-epochs = 10
model = "logreg" # Model to train. Can be "logreg", "squeezenet" or "bert" at the moment.

# Logreg only parameters
scale = "classic" # Scale to use for images.
# classic is 1*28*28 tensors from 28*28 pixel gray scale images.
# larger is 1*224*224 tensors from enlargend 224*224 pixel gray scale images.
# rgb is 3*224*224 tensors from enlargened 224*224 pixel RGB images.

# BERT only parameters
model-name = "prajjwal1/bert-tiny" # Set a larger model if you have access to more GPU resources
num-labels = 2

# Security type, can be "orgfedavg" or "fhefedavg".
sec-type = "orgfedavg" # or "fhefedavg"

# FHE parameters:
scheme = "BFV" # Encryption scheme. Can also be BGV, BFV, CKKS or CKKS-NF
ser-type = "BINARY" # Serialization type. Can also be JSON
ring-dim = 2048 # Ring dimension. Must be power of two, e.g., 2^11 = 2048
plaintext-mod = 40961
chunk-size = 2097152 # Chunk-size is simply how many weights to encrypt at once,
# should be multiple of batchsize for best effect.
# chunk-size = 65536 # Works for BGV/BFV.
num-coeffs = 16 # How many coefficients to use in polynomial encoding.
# num-coeffs should be a power of 2 to fit better with batchsize.
max-deg-int = 10 # Upper bound for degree of integer polynomial in encoding.
no-polynomial-encoding = false # Hvis false bruk polynomial encoding.

# Keygen parameters:
multiplicative-depth = 1 # Level of the scheme
security-level = "128c" # classical bit measured security, e.g., secure as 128-bits AES
# security-level can be "128c", "192c" or "256c".
ek-needed = false # Should evaluation key be generated.
mult-tech = "HPS" # Multiplication technique for BFV, can be HPS or BEHZ.
delta-bits = "high" # Low (15) or high (50) bit count for \Delta in CKKS.
noise-flooding = true # Should noise flooding be used for CKKS?


# [tool.flwr.federations]
# default = "localhost"

# [tool.flwr.federations.localhost]
# options.num-supernodes = 3
# address = "127.0.0.1:9093" # Address and port that flwr run should communicate with.
# insecure = true
