[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bert-orgfedavg"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.18.0",
    "flwr-datasets>=0.5.0",
    "torch>=2.6.0",
    "transformers>=4.30.0,<5.0",
    "evaluate>=0.4.0,<1.0",
    "datasets>=2.0.0, <3.0",
    "scikit-learn>=1.6.1, <2.0",
    "prometheus_client>=0.19.0"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "Kristian Teig Grønvold"

[tool.flwr.app.components]
serverapp = "bert_orgfedavg.server_app:app"
clientapp = "bert_orgfedavg.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 3
fraction-fit = 1
local-epochs = 1
model-name = "prajjwal1/bert-tiny" # Set a larger model if you have access to more GPU resources
num-labels = 2

[tool.flwr.federations]
default = "localhost"

[tool.flwr.federations.localhost]
options.num-supernodes = 3
# Flower defaults to 2 cores per ClientApp. However, using 4 seems to actually be slower.
# options.backend.client-resources.num-cpus = 4 
# each ClientApp assumes to use 4 CPU cores
address = "127.0.0.1:9093" # Address and port that flwr run should communicate with.
insecure = true