[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flwr-decryption-no-server"
version = "1.0.0"
description = ""
license = "Apache-2.0"

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "Kristian Teig Grønvold"

[tool.flwr.app.components]
serverapp = "flwr_decryption_no_server.server_app:app"
clientapp = "flwr_decryption_no_server.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 3
num-ct = 0
ser-type = "BINARY"
num-clients = 2 # Number of clients expected to join.

# [tool.flwr.federations]
# default = "localhost"

# [tool.flwr.federations.localhost]
# options.num-supernodes = 2
# address = "0.0.0.0:10093" # Address and port that flwr run should communicate with.
# insecure = true