[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "squeezenet-secagg"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]==1.20.0",
    "flwr-datasets[vision]==0.5.0",
    "torch==2.8.0",
    "torchvision==0.23.0",
    "prometheus_client>=0.19.0"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "Kristian Teig Grønvold"

[tool.flwr.app.components]
serverapp = "squeezenet_secagg.server_app:app"
clientapp = "squeezenet_secagg.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 3
fraction-fit = 1 # Need all clients to train for experiments.
local-epochs = 1
# Parameters for the SecAgg protocol
reconstruction-threshold = 1.0
max-weight = 12000

[tool.flwr.federations]
default = "localhost"

[tool.flwr.federations.localhost]
options.num-supernodes = 3
address = "127.0.0.1:9093" # Address and port that flwr run should communicate with.
insecure = true